services:
  - type: web
    name: django-web-service
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn project_name.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        value: postgresql://psinous_user:qFfprgCc12pFSXgFPcMJ2F2qiOfbRVzj@dpg-ctjvggjqf0us739eajhg-a/psinous
      - key: DJANGO_SECRET_KEY
        value: django-insecure-2a$shmv=6m0tva@0b-1@)rpq)^x-@m20h=%1n0a&yn!id!7zh=
      - key: DJANGO_DEBUG
        value: "false"
    staticPublishPath: staticfiles
