# Generated by Django 5.1.1 on 2024-10-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("psinous_app", "0003_about_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="title",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
