# Generated by Django 5.1.2 on 2024-10-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psinous_app', '0004_about_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('registration_link', models.URLField(max_length=255)),
                ('event_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='event/')),
            ],
        ),
    ]
