# Generated by Django 5.1.2 on 2024-10-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psinous_app', '0005_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='announcement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcement/')),
            ],
        ),
    ]
