# Generated by Django 5.1.1 on 2024-10-31 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("psinous_app", "0008_event_short_description_alter_event_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=50)),
                ("bio", models.TextField(blank=True, null=True)),
                ("linkedin", models.URLField()),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="members/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="teams/")),
            ],
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("short_text", models.TextField()),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_published", models.BooleanField(default=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="blogs/")),
                (
                    "writer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blogs",
                        to="psinous_app.member",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="member",
            name="team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="psinous_app.team",
            ),
        ),
    ]
