# Generated by Django 5.1.1 on 2024-10-31 17:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("psinous_app", "0009_member_team_blog_member_team"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="name",
        ),
    ]
