# Generated by Django 5.1.2 on 2024-11-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psinous_app', '0012_member_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
