# Generated by Django 5.1.1 on 2024-11-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("psinous_app", "0012_member_university"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="likes",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="views",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
