# Generated by Django 5.1.1 on 2024-11-06 16:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("psinous_app", "0013_blog_likes_blog_views"),
        ("psinous_app", "0013_team_position"),
    ]

    operations = []
