# Generated by Django 5.1.1 on 2024-11-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("psinous_app", "0016_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("subject", models.TextField()),
                ("message", models.TextField()),
            ],
        ),
    ]
