# Generated by Django 5.1.1 on 2024-11-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("psinous_app", "0017_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="message/"),
        ),
        migrations.AddField(
            model_name="message",
            name="sub_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
