# Generated by Django 5.1.2 on 2024-11-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psinous_app', '0019_blog_likes_count_blog_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
