# Generated by Django 5.1.2 on 2024-11-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psinous_app', '0022_event_summary_link_alter_sponsor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='image',
        ),
        migrations.AddField(
            model_name='announcement',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
