# Generated by Django 5.1.1 on 2024-12-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("psinous_app", "0025_memberyear"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="phone_image",
            field=models.ImageField(blank=True, null=True, upload_to="announcement/"),
        ),
    ]
