# Generated by Django 5.1.2 on 2024-12-05 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psinous_app', '0026_announcement_phone_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='short_description',
        ),
    ]
