# Generated by Django 5.1.1 on 2024-12-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("psinous_app", "0028_sponsor_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="phone_image",
            field=models.ImageField(blank=True, null=True, upload_to="about/"),
        ),
    ]
