# Generated by Django 5.1.1 on 2024-12-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("psinous_app", "0029_about_phone_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_finish_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
